version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: weekly, day: monday }
  - package-ecosystem: rust-toolchain
    directory: /
    schedule: { interval: weekly, day: monday }
