# Configuration for cargo-release
allow-branch = ["main"]
pre-release-replacements = [
    # Update version for install script in README
    { file="README.md", search="/releases/download/[^/]+/", replace="/releases/download/{{version}}/" },
    # Bug report template
    { file=".github/ISSUE_TEMPLATE/bug_report.yml", search='v[^ ]+ \(latest\)', replace="v{{version}} (latest)" }
]
# Changelog generation with git-cliff
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
